module.exports={
    publicPath:'/',
    outputDir:'dist',
    assetsDir:"assets",
    runtimeCompiler:true,
    productionSourceMap:false,
    filenameHashing:false,
    lintOnSave:true,
    devServer:{
        open:true,
        host:'0.0.0.0',
        port:8080,
        https:false,
        hotOnly:false,
        proxy:{
            '/api':{
                target:'http://localhost:8443',
                changeOrigin:true,
                pathRewrite:{
                    '^/api':''
                }
            }
        }
    }
}